services:
  mysql-primary:
    image: mysql:8.0
    container_name: mysql-primary
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-primary-data:/var/lib/mysql
      - ./mysql-primary.cnf:/etc/mysql/conf.d/mysql-primary.cnf
      - ./init-primary.sql:/docker-entrypoint-initdb.d/init-primary.sql
    networks:
      - mysql-network
    command: >
      --server-id=1 
      --log-bin=mysql-bin 
      --gtid-mode=ON 
      --enforce-gtid-consistency=ON
      --bind-address=0.0.0.0
      --skip-name-resolve

volumes:
  mysql-primary-data:

networks:
  mysql-network:
    driver: bridge